# https://docs.travis-ci.com/user/reference/overview/ : distributions xenial bionic focal # dist: xenial by default

script:
  #- export CC=gcc-7
  #- export CXX=g++-7
  - ./install-dependencies.sh 
  - make clean
  - make all -j4 
  - make deploy
