name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: ./install-dependencies.sh
    - name: Run compile all
      run: make all -j8
    - name: Run deploy
      run: make deploy
